services:
  app:
    build: .
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    environment:
      PORT: 5000
      DATABASE_URL: postgres://pagespeed_app:pagespeed_admin@postgres/pagespeed_app
    depends_on:
      - postgres
  postgres:
    image: postgres:17-alpine
    # build:
    #   context: ./docker/postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pagespeed_app
      - POSTGRES_PASSWORD=pagespeed_admin
      - POSTGRES_DB=pagespeed_app
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  prisma:
    container_name: prisma
    ports:
      - "5555:5555"
    build:
      context: prisma
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://pagespeed_app:pagespeed_admin@postgres:5432/pagespeed_app
